Repository layer5io/meshery-tmp, pull requests merged in 2020-04, with the labels that each got.

#14 Add the ci job for test the KinD
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: Contribution Allowed, area/ci

#20 Sync the ci config from meshery
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  .github/stale.yml
  .github/workflows/ci.yml
Labels: PR: unreviewed

#21 Release drafter action added
  .github/workflows/release-drafter.yml
Labels: PR: unreviewed

#22 Add release-drafter.yml config file
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: PR: unreviewed

#55 Add arm / arm64 as arch targets
  .goreleaser.yml
Labels: PR: reviewed-approved
